In [6]:
%pip install --upgrade ydata-profiling setuptools

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ydata-profiling in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (4.18.4)
Requirement already satisfied: setuptools in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (84.0.0)
Requirement already satisfied: scipy<1.17,>=1.8 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (1.15.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (3.9.2)
Requirement already satisfied: pydantic<3,>=2 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (2.12.5)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: minify-html>=0.15.0 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.66.3 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from imagehash==4.3.2->ydata-profiling) (11.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.0)
Requirement already satisfied: cycler>=0.10 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.7)
Requirement already satisfied: packaging>=20.0 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2024.1)
Requirement already satisfied: joblib>=0.14.1 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from pydantic<3,>=2->ydata-profiling) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2024.8.30)
Requirement already satisfied: patsy>=0.5.6 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: colorama in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (24.2.0)
Requirement already satisfied: networkx>=2.4 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Requirement already satisfied: puremagic in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.0.0)
Requirement already satisfied: six>=1.5 in C:\Users\91939\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
%pip install "setuptools<70"

Defaulting to user installation because normal site-packages is not writeable
Collecting setuptools<70
  Downloading setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
Downloading setuptools-69.5.1-py3-none-any.whl (894 kB)
   ---------------------------------------- 0.0/894.6 kB ? eta -:--:--
   ---------------------------------------- 0.0/894.6 kB ? eta -:--:--
   ---------------------------------------- 0.0/894.6 kB ? eta -:--:--
   ---------------------------------------- 894.6/894.6 kB 8.1 MB/s  0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 84.0.0
    Uninstalling setuptools-84.0.0:
      Successfully uninstalled setuptools-84.0.0
Successfully installed setuptools-69.5.1
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.13.0 requires setuptools>=77.0.3, but you have setuptools 69.5.1 which is incompatible.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')
df.sample(5)

,student_id,student_name,section,attendance_pct,study_hours_per_week,assignment_score_pct,previous_marks_pct,internal_marks_pct,class_participation_1_5,assignment_completion_pct,previous_gpa_10,absences_count,sleep_hours_per_day,final_marks_pct
450,STU100451,Aarav Jain,C,80.8,8.9,66.8,80.4,76.5,4.3,68.0,5.10,10,6.8,77.1
1028,STU101029,Harsh Das,A,82.0,7.6,85.9,66.6,70.6,5.0,82.5,4.76,10,8.6,80.5
1446,STU101447,Bhavya Iyer,C,100.0,9.3,56.8,72.7,60.9,5.0,75.9,4.50,1,8.5,70.7
1158,STU101159,Riya Iyer,C,58.7,5.2,68.5,71.8,56.8,5.0,71.0,4.91,20,7.4,74.6
459,STU100460,Ishita Mishra,D,81.8,3.3,78.5,81.7,75.5,5.0,74.5,5.27,8,7.2,84.2

In [3]:
from ydata_profiling import ProfileReport
profile = ProfileReport(df, title="My Data Report")

# Save the report to an HTML file
profile.to_file("my_report.html")

C:\Users\91939\AppData\Local\Temp\ipykernel_17548\2408795832.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                                                           | 0/14 [00:00<?, ?it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 22.75it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [4]:
df2 = pd.read_csv('data2.csv')
df2.sample(5)

,student_id,attendance_pct,internal_test_1_pct,internal_test_2_pct,assignment_score_pct,daily_study_hours,previous_year_marks_pct,final_marks_pct
449,S1449,90.0,100.0,95.0,80.0,4.0,85.2,85.0
1160,S2160,92.0,75.0,87.5,70.0,3.0,61.9,76.0
899,S1899,92.0,82.5,75.0,70.0,3.0,82.5,60.0
840,S1840,96.0,100.0,92.5,80.0,3.0,56.2,84.0
1047,S2047,94.0,85.0,82.5,60.0,3.0,73.8,70.0

In [5]:
profile = ProfileReport(df2, title="My Data Report2")

# Save the report to an HTML file
profile.to_file("my_report2.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 7027.32it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]